# Generated by Django 6.0.3 on 2026-03-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_url',
            new_name='parent_url',
        ),
    ]
