# Generated by Django 6.0.3 on 2026-04-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='order',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
