# Generated by Django 6.0.3 on 2026-04-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_categories_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
    ]
