# Generated by Django 6.0.3 on 2026-04-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_categories_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
