# Generated by Django 6.0.3 on 2026-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Інформація')),
                ('description', models.TextField(default='Детальна інформація')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('pages_type', models.CharField(choices=[('delivery', 'Доставка і оплата'), ('contacts', 'Контакти'), ('sizes', 'Розміри'), ('terms', 'Терміни виконання')], default='delivery', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=1)),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
