# Generated by Django 6.0.3 on 2026-06-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ImageField(default=1, upload_to='')),
                ('products', models.ManyToManyField(to='products.product')),
            ],
        ),
    ]
