# Generated by Django 6.0.3 on 2026-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(default='Інформація', max_length=100),
        ),
    ]
