# Generated by Django 6.0.3 on 2026-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
