# Generated by Django 6.0.3 on 2026-07-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=10)),
                ('office', models.CharField(blank=True, max_length=10, null=True)),
                ('entrance', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('PRE', 'Оплата на реквізити'), ('POST', 'Оплата при отриманні')], default='PRE', max_length=10, verbose_name='Спосіб оплати')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product_name', models.CharField(default='Product', max_length=20)),
                ('sizes', models.CharField(blank=True, max_length=10, null=True, verbose_name='Розмір')),
                ('stickers', models.CharField(blank=True, max_length=100, null=True, verbose_name='Стікери')),
                ('count_sticker', models.CharField(blank=True, choices=[(1, '1 принт'), (3, '3 принти')], max_length=20, null=True)),
                ('sticker_position', models.CharField(blank=True, choices=[('FRONT', 'Спереду'), ('BACK', 'Ззаду')], max_length=20, null=True)),
                ('embroidery', models.CharField(blank=True, choices=[('YES', 'З вишивкою'), ('NO', 'Без вишивки')], max_length=20, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product')),
            ],
        ),
    ]
