# Generated by Django 6.0.3 on 2026-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count_sticker',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='embroidery',
            field=models.CharField(default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sizes',
            field=models.CharField(blank=True, max_length=10, verbose_name='Розмір'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sticker_position',
            field=models.CharField(default='Frond', max_length=20),
        ),
    ]
