# Generated by Django 6.0.3 on 2026-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_count_sticker_orderitem_embroidery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count_sticker',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='embroidery',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sizes',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Розмір'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sticker_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
