# Generated by Django 6.0.3 on 2026-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_count_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count_sticker',
            field=models.CharField(blank=True, choices=[('1', '1 принт'), ('3', '3 принти')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='embroidery',
            field=models.CharField(blank=True, choices=[('YES', 'З вишивкою'), ('NO', 'Без вишивки')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sticker_position',
            field=models.CharField(blank=True, choices=[('FRONT', 'Спереду'), ('BACK', 'Ззаду')], max_length=20, null=True),
        ),
    ]
