# Generated by Django 6.0.3 on 2026-05-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_price_orderitem_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='price',
        ),
    ]
