# Generated by Django 6.0.3 on 2026-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_subtotal_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='office',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
