# Generated by Django 6.0.3 on 2026-07-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors/', verbose_name='Приклад кольору')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Товар', max_length=50, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('is_sticker', models.BooleanField(default=False)),
                ('range', models.IntegerField(default=0, verbose_name='Порядок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('print_position_enabled', models.BooleanField(default=False)),
                ('embroidery_enable', models.BooleanField(default=False)),
                ('supports_stickers', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за вишивку')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('IN', '🟢 В наявності'), ('PRE', '🟣 Передзамовлення'), ('OUT', '🔴 Немає в наявності')], default='IN', max_length=3, verbose_name='Статус')),
                ('category', models.ForeignKey(blank=True, default='Brooch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.categories', verbose_name='Категорія')),
                ('colors', models.ManyToManyField(blank=True, to='products.color', verbose_name='Колір')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttype', to='products.categories')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='products.size', verbose_name='Розмір'),
        ),
    ]
