# Generated by Django 6.0.3 on 2026-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_product_slug_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'In stock'), ('PRE', 'Pre order')], default='IN', max_length=3),
        ),
    ]
