# Generated by Django 6.0.3 on 2026-04-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order',
            new_name='position',
        ),
    ]
