# Generated by Django 6.0.3 on 2026-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_order_product_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
