# Generated by Django 6.0.3 on 2026-04-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_categories_slug'),
        ('products', '0008_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.categories', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Товар', max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
