# Generated by Django 6.0.3 on 2026-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_position_product_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'In stock'), ('PRE', 'Pre order')], default='IN', max_length=3, verbose_name='Статус'),
        ),
    ]
