# Generated by Django 6.0.3 on 2026-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'Є в наявності'), ('PRE', 'Передзамовлення')], default='IN', max_length=3, verbose_name='Статус'),
        ),
    ]
