# Generated by Django 6.0.3 on 2026-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IN', 'Є в наявності'), ('PRE', 'Передзамовлення'), ('OUT', 'Немає в наявності')], default='IN', max_length=3, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='products.size'),
        ),
    ]
