# Generated by Django 6.0.3 on 2026-04-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_size_alter_product_status_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
    ]
