# Generated by Django 6.0.3 on 2026-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
