# Generated by Django 6.0.3 on 2026-04-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_color_hex_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.color', verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='products.size', verbose_name='Розмір'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_position',
            field=models.ManyToManyField(blank=True, to='products.printposition', verbose_name='Розміщення'),
        ),
    ]
