# Generated by Django 6.0.3 on 2026-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_printposition_alter_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='print_position',
        ),
        migrations.DeleteModel(
            name='PrintPosition',
        ),
        migrations.AddField(
            model_name='product',
            name='print_position',
            field=models.CharField(choices=[('FRONT', 'Спереду'), ('BACK', 'Ззаду')], default='FRONT', max_length=10, verbose_name='Розміщення'),
        ),
    ]
