# Generated by Django 6.0.3 on 2026-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_print_position_delete_printposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_position_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
