# Generated by Django 6.0.3 on 2026-04-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_print_position_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embroidery',
            field=models.CharField(choices=[('TRUE', 'З вишивкою'), ('FALSW', 'Без вишивки')], default=True, max_length=10, verbose_name='Наявність вишивки'),
        ),
        migrations.AddField(
            model_name='product',
            name='embroidery_enable',
            field=models.BooleanField(default=False),
        ),
    ]
