# Generated by Django 6.0.3 on 2026-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_embroidery_product_embroidery_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embroidery',
            field=models.CharField(choices=[('TRUE', 'З вишивкою'), ('FALSE', 'Без вишивки')], default=True, max_length=10, verbose_name='Наявність вишивки'),
        ),
    ]
