# Generated by Django 6.0.3 on 2026-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_embroidery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supports_stickers',
            field=models.BooleanField(default=False),
        ),
    ]
