# Generated by Django 6.0.3 on 2026-04-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_supports_stickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='embroidery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='print_position',
        ),
    ]
