# Generated by Django 6.0.3 on 2026-05-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_embroidery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Товар', max_length=50, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення')),
                ('range', models.IntegerField(default=0, verbose_name='Порядок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка')),
                ('status', models.CharField(choices=[('IN', 'Є в наявності'), ('PRE', 'Передзамовлення'), ('OUT', 'Немає в наявності')], default='IN', max_length=3, verbose_name='Статус')),
                ('sizes', models.ManyToManyField(blank=True, to='products.size', verbose_name='Розмір')),
            ],
        ),
    ]
