# Generated by Django 6.0.3 on 2026-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_stickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за вишивку'),
        ),
    ]
